import type { AppProps } from 'next/app'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react';
import { ProSidebar, Menu, MenuItem, SubMenu } from 'react-pro-sidebar';

import { baseUrl } from '../services/traveler'

import Loader from "react-loader-spinner"
import "react-loader-spinner/dist/loader/css/react-spinner-loader.css"

import '../styles/globals.css'
import '../styles/bootstrap-night.css';
import 'react-pro-sidebar/dist/css/styles.css';
import axios from 'axios';

interface IProps extends AppProps {
  allowedSpecialEndpoints: string|undefined
}

function MyApp({ Component, pageProps, allowedSpecialEndpoints }: IProps) {

  const [ loading, setLoading ] = useState<boolean>( false );

  const storeManifest = async () => {
    await axios({
        method: 'PUT',
        url: baseUrl + '/api/manifest',
    });
    setLoading(false);
  }

  const trainModel = async () => {
    await axios({
        method: 'PUT',
        url: baseUrl + '/api/ai/training',
    });
    setLoading(false);
  }

  return <div className="app" style={{ 
    height : '100%',
    width : '100%',
    position: 'fixed',
    display: 'flex'
   }}>
    <Head>
      <title>Destiny API Web</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ProSidebar>
      <Menu iconShape="square">
        <MenuItem ><Link href="/" >Destiny Web Api</Link></MenuItem>
        <SubMenu title="User Tools" >
          <MenuItem className="mt-3" ><Link href="/getPlayer" >Search Player</Link></MenuItem>
          <MenuItem className="mt-3" ><Link href="/predictResults" >Match Prediction</Link></MenuItem>
        </SubMenu>
        { allowedSpecialEndpoints && <SubMenu title="Admin Tools" >
          <MenuItem style={{ cursor: 'pointer' }} onClick={ () => { setLoading(true); storeManifest() } }>
            <label style={{float:'left', marginRight: '10px', cursor: 'pointer'}}>Update Manifest</label>
          </MenuItem>
          <MenuItem style={{ cursor: 'pointer' }} onClick={ () => { setLoading(true); trainModel() } }>
            <label style={{float:'left', marginRight: '10px', cursor: 'pointer'}}>Train Ai Model</label>
          </MenuItem>
          <div style={{ marginLeft: '15px' }} >{ loading && <Loader
              type="Puff"
              color="#00BFFF"
              height={15}
              width={15}
          /> }</div>
        </SubMenu> }
      </Menu>
    </ProSidebar>
    <main className={"main-app"} style={{
      padding: '24px',
      flexGrow: 1,
      display: 'flex',
      flexDirection: 'column',
      overflowY: 'auto',
    }}>
        <Component {...pageProps} />
    </main>

  </div>
}

MyApp.getInitialProps = () => {
  const { allowedSpecialEndpoints } = require('../services/apiSecret');
  return { allowedSpecialEndpoints };
}

export default MyApp;