import type { AppProps } from 'next/app'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react';
import { ProSidebar, Menu, MenuItem, SubMenu } from 'react-pro-sidebar';

import { baseUrl } from '../services/traveler'

import Loader from "react-loader-spinner"
import "react-loader-spinner/dist/loader/css/react-spinner-loader.css"

import '../styles/globals.css'
import '../styles/bootstrap-night.css';
import 'react-pro-sidebar/dist/css/styles.css';
import axios from 'axios';

export default function MyApp({ Component, pageProps }: AppProps) {

  const [ loading, setLoading ] = useState<boolean>( false );

  const storeManifest = async () => {
    const response = (await axios({
        method: 'PUT',
        url: baseUrl + '/api/manifest',
    }) ).data;
    setLoading(false);
  }

  return <div className="app" style={{ 
    height : '100%',
    width : '100%',
    position: 'fixed',
    display: 'flex'
   }}>
    <Head>
      <title>Destiny API Web</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ProSidebar>
      <Menu iconShape="square">
        <MenuItem ><Link href="/" > Destiny Web Api </Link></MenuItem>
        <SubMenu title="Tools" >
          <MenuItem><Link href="/getPlayer" > search Player </Link></MenuItem>
          <MenuItem style={{ cursor: 'pointer' }} onClick={ () => { setLoading(true); storeManifest() } }>
            <label style={{float:'left', marginRight: '10px', cursor: 'pointer'}}>update Manifest</label>
            { loading ? <Loader
                type="Puff"
                color="#00BFFF"
                height={15}
                width={15}
            /> : null }
          </MenuItem>
        </SubMenu>
      </Menu>
    </ProSidebar>
    <main className={"main-app"} style={{
      padding: '24px',
      flexGrow: 1,
      display: 'flex',
      flexDirection: 'column',
      overflowY: 'auto',
    }}>
        <Component {...pageProps} />
    </main>

  </div>
}